name: Lint
on: [push]
permissions: write-all

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm install --force 
      
      - name: Install ESLint
        run: npm i typescript && npm install -g eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
        
      - name: Run setup
        run: npm install --save-dev eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - name: Run linters
        run: npm run lint
