name: Lint
on: [push]
permissions: write-all

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm install --force 
      
      - name: Install ESLint
        run: npm install -g eslint prettier

      - name: Run linters
        run: eslint --ignore-path .gitignore --ext .js,.ts,.tsx .
