name: Lint
on: [push]
permissions: write-all

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Set up typescript
        run: npm install --save-dev typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
        
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Install ESLint
        run: npm install -g eslint prettier

      - name: Run linters
        uses: wearerequired/lint-action@v1
        eslint_extensions: js,ts
        prettier_extensions: js,ts
        with:
          eslint: true
          prettier: true
          auto_fix: true
          git_name: "Linter"
          commit_message: "使用 ${linter} 改進代碼質量"
